双十国庆证据补充
evil-huawei/evil-huawei pull request #8
Opened 2019-12-01 15:08 UTC by MlgmXyysd

2019-12-01 15:39 UTC, EvilHuawei requested changes

2019-12-01 15:39 UTC, EvilHuawei commented on README.md
> -- [台湾华为 Facebook 账号庆祝双十国庆【存疑】](./events/台湾华为%20Facebook%20账号庆祝双十国庆【存疑】/)
不要直接修改根目录下的 README，这个是自动生成的。

2019-12-01 15:39 UTC, EvilHuawei commented on events/台湾华为 Facebook 账号庆祝双十国庆【存疑】/README.md
> -# 台湾华为 Facebook 账号庆祝双十国庆【存疑】
目前的存疑点在于双十国庆是否可以庆祝存在一定的争议。

2019-12-01 15:39 UTC, EvilHuawei commented on events/台湾华为 Facebook 账号庆祝双十国庆【存疑】/README.md
> -# 台湾华为 Facebook 账号庆祝双十国庆【存疑】
BTW，这个 Repo 并不打算探讨意识形态和政治的问题，所以客观、谨慎的记录是没有坏处的。

2019-12-01 15:40 UTC, MlgmXyysd commented on events/台湾华为 Facebook 账号庆祝双十国庆【存疑】/README.md
> -# 台湾华为 Facebook 账号庆祝双十国庆【存疑】
那可以改成给“我们的国家”庆祝生日

2019-12-01 15:40 UTC, EvilHuawei commented
补充相关的资料是欢迎的，能帮助增加客观性、严谨性。

2019-12-01 15:41 UTC, MlgmXyysd commented on events/台湾华为 Facebook 账号庆祝双十国庆【存疑】/README.md
> -# 台湾华为 Facebook 账号庆祝双十国庆【存疑】
> 那可以改成给“我们的国家”庆祝生日

https://github.com/MlgmXyysd/Huawei-Taidu/blob/master/Pic/1565687930417.jpeg

2019-12-02 04:58 UTC, sorz commented
直接说「作恶」有点重了，算「争议事件」可能好一些…

2019-12-02 05:23 UTC, MlgmXyysd commented
> 直接说「作恶」有点重了，算「争议事件」可能好一些…

https://github.com/MlgmXyysd/Huawei-Taidu/blob/master/Pic/1565687930417.jpeg

这个应该算作恶了，直接把tw说国家

2019-12-02 06:13 UTC, fanhaozzu commented
如果有内地开发者，我觉得大家还是理智点，这个项目极其有可能是某些敌对势力搞的，抛开这些不说，华为通信越做越好，手机做的也很好。如果列作恶，我觉得谷歌、脸书、亚马逊比这多10倍，谨慎点赞围观，理智思考辨别。

2019-12-02 06:52 UTC, jianxiaoBai commented
真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
如果文中所谓的事件可以称得上 "作恶",  我敢说, 找不到一个不作恶的企业甚至是到个人.

2019-12-02 06:53 UTC, MlgmXyysd commented
> 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.

水军请滚出github

2019-12-02 06:56 UTC, jianxiaoBai commented
> > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> 
> 水军请滚出github

只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?

2019-12-02 06:57 UTC, MlgmXyysd commented
> > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > 
> > 
> > 水军请滚出github
> 
> 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?

恩你这不同意见可真意见

2019-12-02 07:00 UTC, jianxiaoBai commented
> > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > 
> > > 
> > > 水军请滚出github
> > 
> > 
> > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> 
> 恩你这不同意见可真意见

我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.

2019-12-02 07:00 UTC, MlgmXyysd commented
> > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > 
> > > > 
> > > > 水军请滚出github
> > > 
> > > 
> > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > 
> > 
> > 恩你这不同意见可真意见
> 
> 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.

另开pr，请

2019-12-02 07:25 UTC, jianxiaoBai commented
> > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > 
> > > > > 
> > > > > 水军请滚出github
> > > > 
> > > > 
> > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > 
> > > 
> > > 恩你这不同意见可真意见
> > 
> > 
> > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> 
> 另开pr，请

人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.

2019-12-02 07:34 UTC, shichiyu commented
> > > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > > 
> > > > > > 
> > > > > > 水军请滚出github
> > > > > 
> > > > > 
> > > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > > 
> > > > 
> > > > 恩你这不同意见可真意见
> > > 
> > > 
> > > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> > 
> > 
> > 另开pr，请
> 
> 人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.

从客观公正的角度看，我巴不得华为立刻倒闭

2019-12-02 07:35 UTC, MlgmXyysd commented
> > > > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > > > 
> > > > > > > 
> > > > > > > 水军请滚出github
> > > > > > 
> > > > > > 
> > > > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > > > 
> > > > > 
> > > > > 恩你这不同意见可真意见
> > > > 
> > > > 
> > > > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> > > 
> > > 
> > > 另开pr，请
> > 
> > 
> > 人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.
> 
> 从客观公正的角度看，我巴不得华为立刻倒闭

XD，+1，做的事太恶心了

2019-12-02 07:48 UTC, jianxiaoBai commented
> > > > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > > > 
> > > > > > > 
> > > > > > > 水军请滚出github
> > > > > > 
> > > > > > 
> > > > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > > > 
> > > > > 
> > > > > 恩你这不同意见可真意见
> > > > 
> > > > 
> > > > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> > > 
> > > 
> > > 另开pr，请
> > 
> > 
> > 人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.
> 
> 从客观公正的角度看，我巴不得华为立刻倒闭

啧啧啧...

2019-12-02 07:57 UTC, kumgang7879 commented
海狗子无处不在啊，还跑这来吠？

2019-12-02 07:59 UTC, jianxiaoBai commented
> 海狗子无处不在啊，还跑这来吠？

别叫了

2019-12-02 07:59 UTC, MlgmXyysd commented
> > 海狗子无处不在啊，还跑这来吠？
> 
> 别叫了

有完没完了在我pr下面吵？想吵吵自己开pr去

2019-12-02 08:07 UTC, jianxiaoBai commented
> > > 海狗子无处不在啊，还跑这来吠？
> > 
> > 
> > 别叫了
> 
> 有完没完了在我pr下面吵？想吵吵自己开pr去

不吵了

2019-12-02 08:34 UTC, LiuZiqi-dual commented on events/台湾华为 Facebook 账号庆祝双十国庆【存疑】/README.md
> -# 台湾华为 Facebook 账号庆祝双十国庆【存疑】
> 目前的存疑点在于双十国庆是否可以庆祝存在一定的争议。

个人理解确实存在争议，但是鉴于华为一贯以来的宣传立场和伎俩，完全可以算黑历史

2019-12-02 08:35 UTC, LiuZiqi-dual commented
> > > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > > 
> > > > > > 
> > > > > > 水军请滚出github
> > > > > 
> > > > > 
> > > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > > 
> > > > 
> > > > 恩你这不同意见可真意见
> > > 
> > > 
> > > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> > 
> > 
> > 另开pr，请
> 
> 人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.

建议先吃251天的牢饭再来装理客中

2019-12-02 11:31 UTC, shichiyu commented
> > > > > > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 水军请滚出github
> > > > > > > 
> > > > > > > 
> > > > > > > 只要说出一点不同意见就是水军 ? 就应该滚出 github? 你这不是作恶?
> > > > > > 
> > > > > > 
> > > > > > 恩你这不同意见可真意见
> > > > > 
> > > > > 
> > > > > 我其实不是对你提的这个 PR, 而是对这整个项目, 由于项目中没开 issue, 所以在这里发表意见了.
> > > > 
> > > > 
> > > > 另开pr，请
> > > 
> > > 
> > > 人都无完人, 更何况企业, 我这不是为华为辩解什么, 我只是希望大家站在一个客观公正的角度看待每一件事.
> > 
> > 
> > 从客观公正的角度看，我巴不得华为立刻倒闭
> 
> 啧啧啧...

怎么？嫌我不够客观公正？还是说得按你在稿子讲话才能算客观公正？

2019-12-02 11:48 UTC, RuisongZhou commented
有一说一，企业都是以赚钱为目的的，你敢说国内外哪一个私企没有做过所谓的“恶”？只不过做过不让你知道罢了。尤其是当企业有一定规模以后，肯定都会有一些见不得光的事情。
所以华为虽然有一些恶性事件，但大多数都是企业内的个人，而不是整个企业坏掉了。它能改好那必然好，它改不好那肯定有法律取惩罚它。
我看提出这个repo的人是一个中学生，还没有形成完备的价值观，就在这里喷华为，真的是幼稚的行为。等你真正到了工作的年龄，就知道社会上的公司是怎么一回事了

2019-12-02 11:50 UTC, MlgmXyysd commented
> 有一说一，企业都是以赚钱为目的的，你敢说国内外哪一个私企没有做过所谓的“恶”？只不过做过不让你知道罢了。尤其是当企业有一定规模以后，肯定都会有一些见不得光的事情。
> 所以华为虽然有一些恶性事件，但大多数都是企业内的个人，而不是整个企业坏掉了。它能改好那必然好，它改不好那肯定有法律取惩罚它。
> 我看提出这个repo的人是一个中学生，还没有形成完备的价值观，就在这里喷华为，真的是幼稚的行为。等你真正到了工作的年龄，就知道社会上的公司是怎么一回事了

有一说一，这个repo就是集合华为作的恶的事，你要是看其他公司也有你请自己建立对应公司的repo
另外，难道其他公司都作过恶，这个公司就没有“恶”了吗？逻辑感人

2019-12-02 12:27 UTC, ilovehuawei commented
> 有一说一，企业都是以赚钱为目的的，你敢说国内外哪一个私企没有做过所谓的“恶”？只不过做过不让你知道罢了。尤其是当企业有一定规模以后，肯定都会有一些见不得光的事情。
> 所以华为虽然有一些恶性事件，但大多数都是企业内的个人，而不是整个企业坏掉了。它能改好那必然好，它改不好那肯定有法律取惩罚它。
> 我看提出这个repo的人是一个中学生，还没有形成完备的价值观，就在这里喷华为，真的是幼稚的行为。等你真正到了工作的年龄，就知道社会上的公司是怎么一回事了

那你就把这些恶告诉大家，震慑企业，保障员工，推动企业和法制的进步。而不是在这洗地，说什么po主是中学生，我看你连中学生都不如。

2019-12-02 12:47 UTC, smart-z commented
> 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.

你他娘的高级黑么？对的就是对的，错的就是错的。别的企业是你没有列出来，你不想列出别的企业就不允许列华为，你他妈的讲的什么道理？

2019-12-02 12:50 UTC, jianxiaoBai commented
> > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> 
> 你他娘的高级黑么？对的就是对的，错的就是错的。别的企业是你没有列出来，你不想列出别的企业就不允许列华为，你他妈的讲的什么道理？

麻烦先把嘴边的屎擦一下, 谢谢!

2019-12-02 12:51 UTC, smart-z commented
> > 有一说一，企业都是以赚钱为目的的，你敢说国内外哪一个私企没有做过所谓的“恶”？只不过做过不让你知道罢了。尤其是当企业有一定规模以后，肯定都会有一些见不得光的事情。
> > 所以华为虽然有一些恶性事件，但大多数都是企业内的个人，而不是整个企业坏掉了。它能改好那必然好，它改不好那肯定有法律取惩罚它。
> > 我看提出这个repo的人是一个中学生，还没有形成完备的价值观，就在这里喷华为，真的是幼稚的行为。等你真正到了工作的年龄，就知道社会上的公司是怎么一回事了
> 
> 那你就把这些恶告诉大家，震慑企业，保障员工，推动企业和法制的进步。而不是在这洗地，说什么po主是中学生，我看你连中学生都不如。


对的就是对的，错的就是错的。你他妈的讲的什么道理？瑕不掩瑜是情理不是法律，他都触犯法律列还说这不是问题？怎么她妈的还可以用对的来抵消错的这种思路来讲法？你他妈的讲的什么理？

2019-12-02 12:52 UTC, smart-z commented
> > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > 
> > 
> > 你他娘的高级黑么？对的就是对的，错的就是错的。别的企业是你没有列出来，你不想列出别的企业就不允许列华为，你他妈的讲的什么道理？
> 
> 麻烦先把嘴边的屎擦一下, 谢谢!

你心都是黑的，扔你点屎怎么了。

2019-12-02 13:00 UTC, jianxiaoBai commented
> > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > 
> > > 
> > > 你他娘的高级黑么？对的就是对的，错的就是错的。别的企业是你没有列出来，你不想列出别的企业就不允许列华为，你他妈的讲的什么道理？
> > 
> > 
> > 麻烦先把嘴边的屎擦一下, 谢谢!
> 
> 你心都是黑的，扔你点屎怎么了。

把嘴上的屎擦完, 在把满手的屎擦干净.
可能我们对 "恶" 的定义不一样, 争论不出结果.

2019-12-02 13:09 UTC, smart-z commented
> > > > > 真是看热闹不嫌事大, 中国最不缺无脑跟风的人, 一件件鸡毛蒜皮的营销事件都能被定义成 "作恶", 一件件企业内部不和谐都能被叫作恶 , 现在的这个词已经降低到这样的门槛了吗?这不是吹毛求疵是什么?这不是为了蹭热点强行黑而黑又是什么?
> > > > > 如果文中所谓的事件可以称得上 "作恶", 我敢说, 找不到一个不作恶的企业甚至是到个人.
> > > > 
> > > > 
> > > > 你他娘的高级黑么？对的就是对的，错的就是错的。别的企业是你没有列出来，你不想列出别的企业就不允许列华为，你他妈的讲的什么道理？
> > > 
> > > 
> > > 麻烦先把嘴边的屎擦一下, 谢谢!
> > 
> > 
> > 你心都是黑的，扔你点屎怎么了。
> 
> 把嘴上的屎擦完, 在把满手的屎擦干净.
> 可能我们对 "恶" 的定义不一样, 争论不出结果.

我呸，还尼玛“恶”的定义

2019-12-02 13:14 UTC, EvilHuawei commented
楼上各位对「恶」的定义的讨论已经超出这个 PR 的范围，上升到哲学的层面了，在关闭这个 PR 前容我说一句中国的古话：

勿以恶小而为之。

2019-12-02 13:14 UTC, closed without merging